language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
matrix:
  allow_failures:
    - python: "3.3"
    - python: "3.4"
    - python: "pypy"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run manage.py test evap.evaluation evap.fsr evap.contributor evap.results evap.student
after_success:
  - coveralls
